version: "3"
services:

  app:
    build: .
    image: giraldev/appointment-api:latest
    container_name: appointment-api
    restart: always
    ports:
     - "9001:3000"
    depends_on:
      - mysql
